spring.application.name: nsa2-cronjob-example

otel:
  enabled: ${OTEL_ENABLED:false}
  exporter:
    otlp:
      endpoint: http://otel-collector:4318
  logs:
    exporter: otlp
  traces:
    exporter: otlp
  metrics:
    exporter: none
  # javaagent:
  #   enabled: true
  #   jar: ${OTEL_JAVAAGENT_JAR:./javaagent/opentelemetry-javaagent.jar}
  #   extensions: ${OTEL_EXTENSIONS:./javaagent/nsa2-otel-extension-1.0-all.jar}

spring:
  # enable virtual thread
  threads.virtual.enabled: true

  main:
    # disable embedded web server(tomcat)
    web-application-type: none
    # disable banner
    banner-mode: off

spring.security.oauth2.client:
  registration:
    nsa2-cronjob-example:
      provider: ${NSA2_OAUTH_PROVIDER:spring}
      client-id: ${NSA2_OAUTH_CLIENT_ID:nsa2-batch}
      client-secret: ${NSA2_OAUTH_CLIENT_SECRET:secret}
      authorization-grant-type: ${NSA2_OAUTH_GRANT_TYPE:client_credentials}
      scope: ${NSA2_OAUTH_SCOPE:nsa2.admin}

  provider:
    spring:
      issuer-uri: ${NSA2_OAUTH_ISSUER_URI:http://nsa2-auth-server:9000}

logging:
  level:
    org.springframework: INFO
    com.alexamy: DEBUG
    io.opentelemetry: INFO

app:
  services:
    security-admin:
      url: ${SECURITY_ADMIN_SERVICE_URL:http://nsa2-security-admin:8084}