apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "nsa2-cronjob-example.labels" . | nindent 4 }}
  name:  {{ include "nsa2-cronjob-example.fullname" . }}:view
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name:  {{ include "nsa2-cronjob-example.fullname" . }}-config-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "nsa2-cronjob-example.serviceAccountName" . }}